../rtl/ip/compressed_isa/alu.v 
../rtl/ip/compressed_isa/control.v
../rtl/ip/compressed_isa/decoder.v  
../rtl/ip/compressed_isa/dmem.v    
../rtl/ip/compressed_isa/fbuf.v   
../rtl/ip/compressed_isa/forward_mux.v  
../rtl/ip/compressed_isa/gpr.v    
../rtl/ip/compressed_isa/if_id.v  
../rtl/ip/compressed_isa/jump_control.v  
../rtl/ip/compressed_isa/pc_mux.v             
../rtl/ip/compressed_isa/top.v
../rtl/ip/compressed_isa/branch_control.v  
../rtl/ip/compressed_isa/dec.v      
../rtl/ip/compressed_isa/ex_mem.v  
../rtl/ip/compressed_isa/flush.v  
../rtl/ip/compressed_isa/forward.v      
../rtl/ip/compressed_isa/id_ex.v  
../rtl/ip/compressed_isa/imem.v   
../rtl/ip/compressed_isa/mem_wb.v        
../rtl/ip/compressed_isa/program_counter.v  
../rtl/ip/compressed_isa/wb_mux.v
../rtl/ip/compressed_isa/imm.v
../rtl/ip/compressed_isa/hazard_unit.v

