class ic_uncov_seq extends uvm_sequence #(ic_seq_item);
`uvm_object_utils(ic_uncov_seq)

	ic_seq_item seq_item;

	//Constructor
	function new (string name="ic_uncov_seq");
		super.new(name);
	endfunction

	virtual task body();

		repeat(1) begin //Reset
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b0;
					  seq_item.global_int_enable_bit_i  == 48'h00_0000_0000;
					  seq_item.global_int_enable_valid_i== 0;
					  seq_item.ic_ack_read_valid_en     == 0;
					  seq_item.ic_eoi_valid_i	    == 0;
					  seq_item.ic_eoi_id_i	            == '0;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
			  		  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 0;
			  		  seq_item.ext_int44_i	       == 0;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end 
seq_item.print();
		repeat(1) begin //Enabling Lower interrupts
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b1;
					  seq_item.global_int_enable_bit_i  == 48'hFF_0000_0000;
					  seq_item.global_int_enable_valid_i== 1;
					  seq_item.ic_ack_read_valid_en     == 0;
					  seq_item.ic_eoi_valid_i	    == 0;
					  seq_item.ic_eoi_id_i	            == '0;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
					  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 1;
			  		  seq_item.ext_int44_i	       == 1;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end
seq_item.print();

		repeat(1) begin //Enabling Lower interrupts - ACK
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b1;
					  seq_item.global_int_enable_bit_i  == 48'hFF_0000_0000;
					  seq_item.global_int_enable_valid_i== 1;
					  seq_item.ic_ack_read_valid_en     == 1;
					  seq_item.ic_eoi_valid_i	    == 0;
					  seq_item.ic_eoi_id_i	       	    == '0;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
					  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 1;
			  		  seq_item.ext_int44_i	       == 1;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end
		seq_item.print();

		repeat(1) begin //Enabling Lower interrupts - EoI Id
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b1;
					  seq_item.global_int_enable_bit_i  == 48'hFF_0000_0000;
					  seq_item.global_int_enable_valid_i== 1;
					  seq_item.ic_ack_read_valid_en     == 0;
					  seq_item.ic_eoi_valid_i	    == 1;
					  seq_item.ic_eoi_id_i	      	    == 8'h3B;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
					  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 0;
			  		  seq_item.ext_int44_i	       == 1;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end
seq_item.print();

		repeat(1) begin //Enabling Lower interrupts - ACK
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b1;
					  seq_item.global_int_enable_bit_i  == 48'hFF_0000_0000;
					  seq_item.global_int_enable_valid_i== 1;
					  seq_item.ic_ack_read_valid_en     == 1;
					  seq_item.ic_eoi_valid_i	    == 0;
					  seq_item.ic_eoi_id_i	            == 8'h00;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
					  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 0;
			  		  seq_item.ext_int44_i	       == 1;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end
seq_item.print();

		repeat(1) begin //Enabling Lower interrupts - EoI Id
			`uvm_do_with(seq_item,{seq_item.ic_rst==1'b1;
					  seq_item.global_int_enable_bit_i  == 48'hFF_0000_0000;
					  seq_item.global_int_enable_valid_i== 1;
					  seq_item.ic_ack_read_valid_en     == 0;
					  seq_item.ic_eoi_valid_i	    == 1;
					  seq_item.ic_eoi_id_i	       	    == 8'h3C;
					  seq_item.active_lvl_pr_i	    == 8'h00;
					  seq_item.ic_mmr_read_en_i 	    == 0;
					  seq_item.ic_mmr_read_addr_i       == 0;
					  seq_item.ic_mmr_write_en_i	    ==  0;
					  seq_item.ic_mmr_write_addr_i      == '0;
				       	  seq_item.ic_mmr_write_data_i      == '0;
			  		  seq_item.ext_int0_i	       == 0;
			  		  seq_item.ext_int1_i	       == 0;
			  		  seq_item.ext_int2_i	       == 0;
			  		  seq_item.ext_int3_i	       == 0;
					  seq_item.ext_int4_i	       == 0;
			  		  seq_item.ext_int5_i	       == 0;
			  		  seq_item.ext_int6_i	       == 0;
			  		  seq_item.ext_int7_i	       == 0;
			  		  seq_item.ext_int8_i	       == 0;
			  		  seq_item.ext_int9_i	       == 0;
			  		  seq_item.ext_int10_i	       == 0;
			  		  seq_item.ext_int11_i	       == 0;
			  		  seq_item.ext_int12_i	       == 0;
			  		  seq_item.ext_int13_i	       == 0;
			  		  seq_item.ext_int14_i	       == 0;
			  		  seq_item.ext_int15_i	       == 0;
			  		  seq_item.ext_int16_i	       == 0;
			  		  seq_item.ext_int17_i	       == 0;
			  		  seq_item.ext_int18_i	       == 0;
			  		  seq_item.ext_int19_i	       == 0;
			  		  seq_item.ext_int20_i	       == 0;
			  		  seq_item.ext_int21_i	       == 0;
			  		  seq_item.ext_int22_i	       == 0;
			  		  seq_item.ext_int23_i	       == 0;
			  		  seq_item.ext_int24_i	       == 0;
			  		  seq_item.ext_int25_i	       == 0;
			  		  seq_item.ext_int26_i	       == 0;
			  		  seq_item.ext_int27_i	       == 0;
			  		  seq_item.ext_int28_i	       == 0;
			  		  seq_item.ext_int29_i	       == 0;
			  		  seq_item.ext_int30_i	       == 0;
			  		  seq_item.ext_int31_i	       == 0;
			  		  seq_item.ext_int32_i	       == 0;
			  		  seq_item.ext_int33_i	       == 0;
			  		  seq_item.ext_int34_i	       == 0;
			  		  seq_item.ext_int35_i	       == 0;
			  		  seq_item.ext_int36_i	       == 0;
			  		  seq_item.ext_int37_i	       == 0;
			  		  seq_item.ext_int38_i	       == 0;
			  		  seq_item.ext_int39_i	       == 0;
			  		  seq_item.ext_int40_i	       == 0;
			  		  seq_item.ext_int41_i	       == 0;
			  		  seq_item.ext_int42_i	       == 0;
			  		  seq_item.ext_int43_i	       == 0;
			  		  seq_item.ext_int44_i	       == 0;
			  		  seq_item.ext_int45_i	       == 0;
			  		  seq_item.ext_int46_i	       == 0;
//			  		  seq_item.ext_int47_i	       == 0;
			  		  seq_item.dbg_mode_valid_i    == 0;
					}); 
		end
//seq_item.print();

	endtask
endclass
//#####################################################
