//ic_top is top module of ir,pr and irq. 
 module ic_top(input ic_clk,
  			    input ic_rst,//acive low clock
			   	input ic_rst_ack,//soft reset
				input ack_in,//ack in from core
				input [7:0] ack_id,//id from core
				input [47:0] interrupt_enable,//enable fro mmr
				input  ext_int0,//external interrupts(48)
				input  ext_int1,
				input  ext_int2,
				input  ext_int3,
				input  ext_int4,
				input  ext_int5,
				input  ext_int6,
				input  ext_int7,
				input  ext_int8,
				input  ext_int9,
				input  ext_int10,
				input  ext_int11,
				input  ext_int12,
				input  ext_int13,
				input  ext_int14,
				input  ext_int15,
				input  ext_int16,
				input  ext_int17,
				input  ext_int18,
				input  ext_int19,
				input  ext_int20,
				input  ext_int21,
				input  ext_int22,
				input  ext_int23,
				input  ext_int24,
				input  ext_int25,
				input  ext_int26,
				input  ext_int27,
				input  ext_int28,
				input  ext_int29,
				input  ext_int30,
				input  ext_int31,						  
				input  ext_int32,
				input  ext_int33,
				input  ext_int34,
				input  ext_int35,
				input  ext_int36,
				input  ext_int37,
				input  ext_int38,
				input  ext_int39,
				input  ext_int40,
				input  ext_int41,
				input  ext_int42,
				input  ext_int43,
				input  ext_int44,
				input  ext_int45,
				input  ext_int46,
				input  ext_int47,
				input [7:0] int0_lp_i,//interrupts lvl/pr values from mmr
				input [7:0] int1_lp_i,
				input [7:0] int2_lp_i,
				input [7:0] int3_lp_i,
				input [7:0] int4_lp_i,
				input [7:0] int5_lp_i,
				input [7:0] int6_lp_i,
				input [7:0] int7_lp_i,
				input [7:0] int8_lp_i,
				input [7:0] int9_lp_i,
				input [7:0] int10_lp_i,
				input [7:0] int11_lp_i,
				input [7:0] int12_lp_i,
				input [7:0] int13_lp_i,
				input [7:0] int14_lp_i,
				input [7:0] int15_lp_i,
				input [7:0] int16_lp_i,
				input [7:0] int17_lp_i,
				input [7:0] int18_lp_i,
				input [7:0] int19_lp_i,
				input [7:0] int20_lp_i,
				input [7:0] int21_lp_i,
				input [7:0] int22_lp_i,
				input [7:0] int23_lp_i,
				input [7:0] int24_lp_i,
				input [7:0] int25_lp_i,
				input [7:0] int26_lp_i,
				input [7:0] int27_lp_i,
				input [7:0] int28_lp_i,
				input [7:0] int29_lp_i,
				input [7:0] int30_lp_i,
				input [7:0] int31_lp_i,
				input [7:0] int32_lp_i,
				input [7:0] int33_lp_i,
				input [7:0] int34_lp_i,
				input [7:0] int35_lp_i,
				input [7:0] int36_lp_i,
				input [7:0] int37_lp_i,
				input [7:0] int38_lp_i,
				input [7:0] int39_lp_i,
				input [7:0] int40_lp_i,
				input [7:0] int41_lp_i,
				input [7:0] int42_lp_i,
				input [7:0] int43_lp_i,
				input [7:0] int44_lp_i,
				input [7:0] int45_lp_i,
				input [7:0] int46_lp_i,
				input [7:0] int47_lp_i,
				input [7:0] threshold,
				output irq_request,//request to core
				output [7:0]out_id,//id to core
				output [7:0]interrupt_out,//interrupts lvl/pr value to core
				output [47:0]interrupt_pending_o//pending vectore to mmr
				);

				wire [7:0]interrupt_id;//internal wires
				wire [7:0]interrupt;
				wire [47:0]interrupt_pending_w;
				wire highest_int_valid;

interrupt_receive DUT1(.ic_clk (ic_clk),//ir instantiation
					   .ic_rst(ic_rst),
					   .ack_in(irq_request),
					   .ack_id(out_id),
					   .interrupt_enable(interrupt_enable),
					   .interrupt_pending_o(interrupt_pending_w),
					   .ext_int0(ext_int0), 
					   .ext_int1(ext_int1), 
					   .ext_int2(ext_int2), 
					   .ext_int3(ext_int3), 
					   .ext_int4(ext_int4), 
					   .ext_int5(ext_int5), 
					   .ext_int6(ext_int6), 
					   .ext_int7(ext_int7), 
					   .ext_int8(ext_int8), 
					   .ext_int9(ext_int9), 
					   .ext_int10(ext_int10), 
					   .ext_int11(ext_int11), 
					   .ext_int12(ext_int12), 
					   .ext_int13(ext_int13), 
					   .ext_int14(ext_int14), 
					   .ext_int15(ext_int15), 
					   .ext_int16(ext_int16), 
					   .ext_int17(ext_int17), 
					   .ext_int18(ext_int18), 
					   .ext_int19(ext_int19), 
					   .ext_int20(ext_int20), 
					   .ext_int21(ext_int21), 
					   .ext_int22(ext_int22), 
					   .ext_int23(ext_int23), 
					   .ext_int24(ext_int24), 
					   .ext_int25(ext_int25), 
					   .ext_int26(ext_int26), 
					   .ext_int27(ext_int27), 
					   .ext_int28(ext_int28), 
					   .ext_int29(ext_int29), 
					   .ext_int30(ext_int30), 
					   .ext_int31(ext_int31), 
					   .ext_int32(ext_int32), 
					   .ext_int33(ext_int33), 
					   .ext_int34(ext_int34), 
					   .ext_int35(ext_int35), 
					   .ext_int36(ext_int36), 
					   .ext_int37(ext_int37), 
					   .ext_int38(ext_int38), 
					   .ext_int39(ext_int39), 
					   .ext_int40(ext_int40), 
					   .ext_int41(ext_int41), 
					   .ext_int42(ext_int42), 
					   .ext_int43(ext_int43), 
					   .ext_int44(ext_int44), 
					   .ext_int45(ext_int45), 
					   .ext_int46(ext_int46), 
					   .ext_int47(ext_int47));

ic_pr  DUT2(.ic_clk(ic_clk),//pr instantiation 
            .ic_rst(ic_rst),
			.int_pending_i(interrupt_pending_w),
		    .int0_lp_i(int0_lp_i),	
		    .int1_lp_i(int1_lp_i),	
		    .int2_lp_i(int2_lp_i),	
		    .int3_lp_i(int3_lp_i),	
		    .int4_lp_i(int4_lp_i),	
		    .int5_lp_i(int5_lp_i),	
		    .int6_lp_i(int6_lp_i),	
		    .int7_lp_i(int7_lp_i),	
		    .int8_lp_i(int8_lp_i),	
		    .int9_lp_i(int9_lp_i),	
		    .int10_lp_i(int10_lp_i),	
		    .int11_lp_i(int11_lp_i),	
		    .int12_lp_i(int12_lp_i),	
		    .int13_lp_i(int13_lp_i),	
		    .int14_lp_i(int14_lp_i),	
		    .int15_lp_i(int15_lp_i),	
		    .int16_lp_i(int16_lp_i),	
		    .int17_lp_i(int17_lp_i),	
		    .int18_lp_i(int18_lp_i),	
		    .int19_lp_i(int19_lp_i),	
		    .int20_lp_i(int20_lp_i),	
		    .int21_lp_i(int21_lp_i),	
		    .int22_lp_i(int22_lp_i),	
		    .int23_lp_i(int23_lp_i),	
		    .int24_lp_i(int24_lp_i),	
		    .int25_lp_i(int25_lp_i),	
		    .int26_lp_i(int26_lp_i),	
		    .int27_lp_i(int27_lp_i),	
		    .int28_lp_i(int28_lp_i),	
		    .int29_lp_i(int29_lp_i),	
		    .int30_lp_i(int30_lp_i),	
		    .int31_lp_i(int31_lp_i),	
		    .int32_lp_i(int32_lp_i),	
		    .int33_lp_i(int33_lp_i),	
		    .int34_lp_i(int34_lp_i),	
		    .int35_lp_i(int35_lp_i),	
		    .int36_lp_i(int36_lp_i),	
		    .int37_lp_i(int37_lp_i),	
		    .int38_lp_i(int38_lp_i),	
		    .int39_lp_i(int39_lp_i),	
		    .int40_lp_i(int40_lp_i),	
		    .int41_lp_i(int41_lp_i),	
		    .int42_lp_i(int42_lp_i),	
		    .int43_lp_i(int43_lp_i),	
		    .int44_lp_i(int44_lp_i),	
		    .int45_lp_i(int45_lp_i),	
		    .int46_lp_i(int46_lp_i),	
		    .int47_lp_i(int47_lp_i),	
			.interrupt_id_o(interrupt_id),
			.highest_pending_lvl_pr_o(interrupt),
			.highest_pending_valid(highest_int_valid)
			);

ic_irq DUT3(.ic_clk(ic_clk),//irg instantiation
            .ic_rst(ic_rst),
			.ic_rst_ack(ic_rst_ack),
			.interrupt(interrupt),
			.interrupt_id(interrupt_id),
			.highest_int_valid(highest_int_valid),
			.interrupt_pending_en(interrupt_pending_w),
			.active_lvl(threshold),
			.irq_request(irq_request),
			.out_id(out_id),
			.interrupt_out(interrupt_out));
			assign interrupt_pending_o=interrupt_pending_w;
  endmodule


