merge -out cov_merged_output test*
load -run ./cov_work/scope/cov_merged_output/
exclude -inst zic_mmr_top -toggle {zic_mmr_read_data_o[8-31]}
exclude -inst zic_mmr_top -toggle {zic_cfg_w[0-7]}
exclude -inst zic_mmr_top -toggle {zic_info_w[0-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {zic_cfg_o[0-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {zic_info_o[0-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_cfg_inst -toggle {zic_cfg_o[0-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_info_inst -toggle {zic_info_o[0-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {zic_cfg_i[0-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {zic_info_i[0-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq0_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq0_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq1_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq1_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq2_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq2_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq3_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq3_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq4_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq4_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq5_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq5_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq6_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq6_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq7_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq7_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq8_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq8_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq9_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq9_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq10_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq10_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq11_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq11_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq12_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq12_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq13_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq13_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq14_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq14_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq15_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq15_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq16_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq16_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq17_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq17_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq18_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq18_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq19_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq19_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq20_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq20_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq21_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq21_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq22_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq22_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq23_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq23_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq24_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq24_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq25_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq25_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq26_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq26_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq27_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq27_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq28_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq28_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq29_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq29_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq30_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq30_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq31_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq31_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq32_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq32_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq33_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq33_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq34_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq34_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq35_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq35_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq36_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq36_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq37_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq37_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq38_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq38_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq39_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq39_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq40_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq40_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq41_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq41_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq42_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq42_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq43_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq43_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq44_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq44_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq45_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq45_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq46_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq46_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq47_ctrl_i[1-7]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {irq47_ctrl_i[9-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {zic_mmr_read_data_o[8-31]}
exclude -inst zic_mmr_top.zic_mmr_op_mux_inst -toggle {zic_mmr_read_data_r[8-31]}
exclude -inst zic_mmr_top -toggle {irq0_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq1_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq2_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq3_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq4_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq5_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq6_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq7_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq8_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq9_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq10_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq11_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq12_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq13_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq14_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq15_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq16_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq17_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq18_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq19_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq20_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq21_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq22_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq23_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq24_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq25_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq26_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq27_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq28_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq29_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq30_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq31_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq32_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq33_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq34_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq35_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq36_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq37_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq38_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq39_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq40_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq41_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq42_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq43_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq44_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq45_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq46_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq47_ctrl_o[1-7]}
exclude -inst zic_mmr_top -toggle {irq0_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq0_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq1_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq1_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq2_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq2_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq3_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq3_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq4_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq4_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq5_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq5_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq6_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq6_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq7_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq7_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq8_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq8_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq9_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq9_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq10_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq10_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq11_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq11_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq12_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq12_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq13_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq13_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq14_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq14_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq15_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq15_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq16_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq16_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq17_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq17_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq18_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq18_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq19_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq19_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq20_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq20_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq21_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq21_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq22_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq22_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq23_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq23_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq24_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq24_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq25_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq25_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq26_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq26_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq27_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq27_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq28_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq28_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq29_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq29_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq30_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq30_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq31_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq31_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq32_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq32_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq33_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq33_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq34_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq34_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq35_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq35_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq36_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq36_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq37_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq37_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq38_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq38_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq39_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq39_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq40_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq40_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq41_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq41_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq42_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq42_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq43_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq43_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq44_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq44_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq45_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq45_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq46_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq46_ctrl_w[9-19]}
exclude -inst zic_mmr_top -toggle {irq47_ctrl_w[1-7]}
exclude -inst zic_mmr_top -toggle {irq47_ctrl_w[9-19]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq0_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq0_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq1_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq1_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq2_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq2_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq3_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq3_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq4_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq4_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq5_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq5_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq6_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq6_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq7_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq7_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq8_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq8_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq9_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq9_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq10_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq10_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq11_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq11_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq12_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq12_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq13_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq13_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq14_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq14_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq15_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq15_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq16_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq16_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq17_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq17_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq18_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq18_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq19_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq19_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq20_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq20_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq21_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq21_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq22_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq22_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq23_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq23_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq24_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq24_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq25_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq25_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq26_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq26_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq27_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq27_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq28_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq28_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq29_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq29_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq30_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq30_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq31_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq31_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq32_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq32_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq33_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq33_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq34_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq34_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq35_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq35_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq36_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq36_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq37_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq37_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq38_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq38_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq39_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq39_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq40_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq40_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq41_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq41_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq42_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq42_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq43_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq43_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq44_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq44_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq45_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq45_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq46_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq46_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq47_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst -toggle {irq47_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq0_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq0_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq1_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq1_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq2_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq2_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq3_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq3_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq4_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq4_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq5_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq5_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq6_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq6_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq7_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq7_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq8_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq8_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq9_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq9_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq10_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq10_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq11_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq11_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq12_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq12_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq13_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq13_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq14_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq14_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq15_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq15_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq16_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq16_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq17_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq17_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq18_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq18_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq19_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq19_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq20_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq20_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq21_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq21_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq22_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq22_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq23_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq23_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq24_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq24_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq25_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq25_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq26_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq26_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq27_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq27_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq28_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq28_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq29_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq29_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq30_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq30_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq31_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq31_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq32_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq32_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq33_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq33_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq34_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq34_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq35_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq35_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq36_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq36_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq37_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq37_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq38_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq38_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq39_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq39_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq40_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq40_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq41_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq41_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq42_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq42_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq43_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq43_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq44_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq44_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq45_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq45_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq46_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq46_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq47_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst -toggle {irq47_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_0_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_1_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_2_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_3_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_4_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_5_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_6_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_7_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_8_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_9_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_10_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_11_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_12_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_13_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_14_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_15_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_16_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_17_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_18_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_19_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_20_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_21_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_22_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_23_ctrl -toggle {zic_ctl_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_irq_ctrl_o[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_irq_ctrl_o[9-31]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_ie_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_ip_mmr[1-7]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_attr_mmr[0-5]}
exclude -inst zic_mmr_top.zic_mmr_reg_file_inst.zic_mmr_ctrl_inst.irq_24_ctrl -toggle {zic_ctl_mmr[1-7]}

report -detail -all -text -out cov_report.txt
report -detail -text -out cov_uncovered_report.txt
report -detail -html -out ./cov_report_html
