interface zic_mem_intf(input logic clk,rst);

  logic        zic_mmr_write_en_i ;
  logic [15:0] zic_mmr_write_addr_i;
  logic [31:0] zic_mmr_write_data_i;
  logic        zic_mmr_read_en_i;
  logic [15:0] zic_mmr_read_addr_i;
  logic [7:0]  zic_ack_int_id_i;
  logic        zic_ack_write_valid_i;
  logic        zic_ack_read_valid_en;
  logic        zic_eoi_valid_i; 
  logic [7:0]  zic_eoi_id_i;
  logic        zic_nxtp_valid_i;
  logic [7:0]  zic_nxtp_id_i;
  logic        zic_int_pending_valid_i;
  logic [47:0] zic_int_pending_bit_i;
  logic [47:0] global_int_enable_bit_i;
  logic        global_int_enable_valid_i;
  logic [31:0] zic_mmr_read_data_o;
  logic [7:0]  zic_ack_int_id_o;
  logic        zic_ack_o;
  logic        zic_eoi_o;
  logic [7:0] irq0_ctrl_o;
  logic [7:0] irq1_ctrl_o;
  logic [7:0] irq2_ctrl_o;
  logic [7:0] irq3_ctrl_o;
  logic [7:0] irq4_ctrl_o;
  logic [7:0] irq5_ctrl_o;
  logic [7:0] irq6_ctrl_o;
  logic [7:0] irq7_ctrl_o;
  logic [7:0] irq8_ctrl_o;
  logic [7:0] irq9_ctrl_o;
  logic [7:0] irq10_ctrl_o;
  logic [7:0] irq11_ctrl_o;
  logic [7:0] irq12_ctrl_o;
  logic [7:0] irq13_ctrl_o;
  logic [7:0] irq14_ctrl_o;
  logic [7:0] irq15_ctrl_o;
  logic [7:0] irq16_ctrl_o;
  logic [7:0] irq17_ctrl_o;
  logic [7:0] irq18_ctrl_o;
  logic [7:0] irq19_ctrl_o;
  logic [7:0] irq20_ctrl_o;
  logic [7:0] irq21_ctrl_o;
  logic [7:0] irq22_ctrl_o;
  logic [7:0] irq23_ctrl_o;
  logic [7:0] irq24_ctrl_o;
  logic [7:0] irq25_ctrl_o;
  logic [7:0] irq26_ctrl_o;
  logic [7:0] irq27_ctrl_o;
  logic [7:0] irq28_ctrl_o;
  logic [7:0] irq29_ctrl_o;
  logic [7:0] irq30_ctrl_o;
  logic [7:0] irq31_ctrl_o;
  logic [7:0] irq32_ctrl_o;
  logic [7:0] irq33_ctrl_o;
  logic [7:0] irq34_ctrl_o;
  logic [7:0] irq35_ctrl_o;
  logic [7:0] irq36_ctrl_o;
  logic [7:0] irq37_ctrl_o;
  logic [7:0] irq38_ctrl_o;
  logic [7:0] irq39_ctrl_o;
  logic [7:0] irq40_ctrl_o;
  logic [7:0] irq41_ctrl_o;
  logic [7:0] irq42_ctrl_o;
  logic [7:0] irq43_ctrl_o;
  logic [7:0] irq44_ctrl_o;
  logic [7:0] irq45_ctrl_o;
  logic [7:0] irq46_ctrl_o;
  logic [7:0] irq47_ctrl_o;

endinterface
