#include "peripheral.h"


/* ============================================================
 *  Pending Retention Until Service Completion
 *
 * Verify that the pending interrupt state is retained according
 * to the implemented level/edge semantics until the required
 * service completion.
 *
 * Test IRQ:
 *
 *     IRQ10
 *
 * Priority:
 *
 *     15
 *
 * CTL:
 *
 *     0xF3
 *
 *
 * Expected sequence:
 *
 *     1. IRQ10 is generated by SV.
 *     2. IRQ10 becomes pending.
 *     3. IRQ10 is selected.
 *     4. Service completion is intentionally delayed.
 *     5. ACK is observed.
 *     6. EOI is observed.
 *     7. Pending/request behavior is checked at each stage.
 *
 * The exact pending behavior after ACK depends on whether the
 * configured source is level or edge triggered and the RTL
 * implementation.
 *
 * ============================================================ */


/* ============================================================
 * Expected values
 * ============================================================ */

#define EXP_IRQ10_ENABLE_VALUE     0x01U

/*
 * IRQ10 priority = 15
 */
#define EXP_IRQ10_CTL_VALUE        0xF3U


/* ============================================================
 * GPIO PINMUX
 * ============================================================ */

#define EXP_GPIO_PINMUX0_VALUE    150994944U
#define EXP_GPIO_PINMUX1_VALUE    585U


int main(void)
{
    uint32_t actual_value;


    /* ============================================================
     * Test Start
     * ============================================================ */

    info_print(0x0000);


    /* ============================================================
     * Enable Global Machine Interrupt
     *
     * mstatus.MIE = bit[3]
     * ============================================================ */

    asm volatile (
        "li t0, 0x8\n"
        "csrrs x0, mstatus, t0\n"
    );


    /* ============================================================
     * Enable Machine External Interrupt
     *
     * Keep existing configuration.
     *
     * 0xFC000000
     * ============================================================ */

    asm volatile (
        "li t0, 0xFC000000\n"
        "csrrs x0, mie, t0\n"
    );


    info_print(0x1111);


    /* ============================================================
     * GPIO PINMUX Configuration
     * ============================================================ */

    mmio_write(
        GPIO_BASE_ADDR + GPIO_PINMUX0_ADDR,
        EXP_GPIO_PINMUX0_VALUE
    );

    mmio_write(
        GPIO_BASE_ADDR + GPIO_PINMUX1_ADDR,
        EXP_GPIO_PINMUX1_VALUE
    );


    info_print(0x2000);


    /* ============================================================
     * Enable IRQ10
     * ============================================================ */

    mmio_write(
        IRQ10_ENABLE_REG_ADDR,
        EXP_IRQ10_ENABLE_VALUE
    );


    /* ============================================================
     * Read IRQ10 ENABLE
     * ============================================================ */

    actual_value = mmio_read(
        IRQ10_ENABLE_REG_ADDR
    );


    if (actual_value != EXP_IRQ10_ENABLE_VALUE)
        error_print(0);
    else
        info_print(1);


    /* ============================================================
     * Configure IRQ10
     *
     * Priority = 15
     * CTL      = 0xF3
     * ============================================================ */

    mmio_write(
        IRQ10_CTL_REG_ADDR,
        EXP_IRQ10_CTL_VALUE
    );


    /* ============================================================
     * Read IRQ10 CTL
     * ============================================================ */

    actual_value = mmio_read(
        IRQ10_CTL_REG_ADDR
    );


    if (actual_value != EXP_IRQ10_CTL_VALUE)
        error_print(1);
    else
        info_print(2);


    /* ============================================================
     * Configuration Complete
     * ============================================================ */

    info_print(0x2222);

    send_handshake_to_sv(1);


    info_print(0x3000);


    /* ============================================================
     * PENDING PHASE
     *
     * Expected:
     *
     *     pending[10] = 1
     *
     * IRQ10 should become the highest eligible interrupt.
     *
     * Expected:
     *
     *     current_int_id_o = IRQ10_ID
     *     interrupt_request_o = 1
     *
     * ============================================================ */

    info_print(0x3010);



    info_print(0x3020);


  

    /* ============================================================
     * Test Complete
     * ============================================================ */

    info_print(0x7038);


}
